CC = gcc

build_overflow:
	$(CC) overflow_test.c -o overflow_test

build_XXA:
	$(CC) XXA_test.c -o XXA_test

build_print_mem:
	$(CC) mem_print_test.c -o mem_print_test

build_sscanf_test:
	$(CC) sscanf_test.c -o sscanf_test